---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-env-secrets
  namespace: monitoring
spec:
  encryptedData:
    DISCORD_DEFAULT_WEBHOOK_URL: AgAp9SQQJuWFkOC5o6RBk/JUnykMCB1vsVvQbG2HewK/abnCIQMh8HCSLJcCSs27hCuqHQkM1m73/jIAB7PtUKYRPdwHvK/MNY/wxqxB/VRCDEfEgIFsg5BuSeLeS4bly++KORdFpe+FPVJRihNtGnfVjyE02drkMq1kNJzR0ewatwRtdincIY5Sx/q7M2WoRSH4PLjvDPwzzu3xPS+2YT9N13g+g9jMHeQHtwgRxbnjC5Zc3zMBfiacAPsWH/xKAZ3QZdBuL7RjjvlJ25eUyKYl2RCw9ogDjRtYits4tOf2Dgglz1PFyTCFOp4POgSUZPR5zcQ+DOZI0Aenoxy+6blUJp5WQAPqwLJcdDmPoqzTKThmF7btkEksOFPMeh66fm14dbbOmsKX4Gq/izKBzeuvxo0IicdxdySJJ00Wx5gbEpAa27lG67VNF4IpbmldI8p4Xw1Xz8uQkpL+614qHVZrDNEAHaa3GYeLFZBkspIUmagZGB5QjT+rCXeLSfPza9zibJHqXM8VYdh/midOcV04vfdd4ChKVbHx++KglP1ZlgA/VbmSPv4+23QnIHuytgMq9D0djk9zmYUmfHgDTIoNmBam9euZKj87le7OktB8Pf8PTJL5wmMuqmfbP0Pjx1e6HP7j6KmvuPMRVi485/zOpe7tFSXj2KtDVfo3W1TPoejXPqyWo1qq9C2C2xTMa+BfVw0ofYDN20QKTnkroc1OAz++5r3B6XFYeEZz7fu7QpEe3C1lp3iaXlnKOS9AJxE2d5KYsT5aLoZAq0Cg6bVblMKWWc6WZ+SWT9d3sgguIE5l9nUPmOHmmgARwGBhtCHkm0S+MB5D6Gml/kl1buQA2alKewdyPwqm
  template:
    metadata:
      name: alertmanager-env-secrets
      namespace: monitoring
