apiVersion: v1
kind: Service
metadata:
  name: seminar-flow-service
spec:
  selector:
    app: seminar-flow-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
