apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- sealed-secret.yaml

images:
- name: seminar-flow
  newName: asia-northeast3-docker.pkg.dev/seminar-flow-2606/seminar-flow/seminar-flow
  newTag: 7a40922fa3eae9422f6f0cefc522859fccea19fd
