apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- sealed-secret.yaml

namePrefix: dev-

images:
- name: seminar-flow
  newName: asia-northeast3-docker.pkg.dev/seminar-flow-2606/seminar-flow/seminar-flow
  newTag: c362db53a8295e3bdbae824625d1cab905d0357f
