apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - sealed-secret.yaml

namePrefix: dev-

images:
  - name: seminar-flow
    newName: asia-northeast3-docker.pkg.dev/seminar-flow-project/seminar-flow/seminar-flow
    newTag: dev
